// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0TrNT7KZY1dV_lb-u1PUu9VY5qiLpkLw',
    appId: '1:763479566523:web:fa7c650392a8f38d7a219e',
    messagingSenderId: '763479566523',
    projectId: 'bitfitx-social-f9219',
    authDomain: 'bitfitx-social-f9219.firebaseapp.com',
    storageBucket: 'bitfitx-social-f9219.appspot.com',
    measurementId: 'G-JX7Y0E1XPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeTV8zdB5tRMZvv935GViTq9Dyh3l4gfA',
    appId: '1:763479566523:android:7c2f23d19c176c1b7a219e',
    messagingSenderId: '763479566523',
    projectId: 'bitfitx-social-f9219',
    storageBucket: 'bitfitx-social-f9219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_XAryhE0A1x0ihysTQ-5OOtS-fg3JVw',
    appId: '1:763479566523:ios:b0bddec503e0fbff7a219e',
    messagingSenderId: '763479566523',
    projectId: 'bitfitx-social-f9219',
    storageBucket: 'bitfitx-social-f9219.appspot.com',
    iosBundleId: 'com.example.bitfitxProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4_XAryhE0A1x0ihysTQ-5OOtS-fg3JVw',
    appId: '1:763479566523:ios:99ba6e7a410e43da7a219e',
    messagingSenderId: '763479566523',
    projectId: 'bitfitx-social-f9219',
    storageBucket: 'bitfitx-social-f9219.appspot.com',
    iosBundleId: 'com.example.bitfitxProject.RunnerTests',
  );
}
